### ISSUE TITLE
Introduce `FOLDER_TREE_LENGTH` config parameter on `scrapy_folder_tree.FilesHashTreePipeline`

### ISSUE THREAD

**Issue by sp1thas** [sp1thas/scrapy-folder-tree#1]
Given this filename: `abcdefg.png` and `FOLDER_TREE_LENGTH=2`

Currently, when using the `scrapy_folder_tree.FilesHashTreePipeline` pipeline, the file path will look like `a/b/abcdefg.png`.

An extra config value (`FOLDER_TREE_LENGTH`) should be added similar to `FOLDER_TREE_LENGTH` in order to allow the user to specify the folder length. For example, if `FOLDER_TREE_LENGTH` is equal to `2`, the file path should look like `ab/cd/abcdefg.png` etc.

In order to support this functionality, the extra config should be added [here](https://github.com/sp1thas/scrapy-folder-tree/blob/master/src/scrapy_folder_tree/config.py) and the filename should be split, based on the `FOLDER_TREE_LENGTH` [here](https://github.com/sp1thas/scrapy-folder-tree/blob/master/src/scrapy_folder_tree/trees/hash.py#L11).

**Comment by Simba-97** [comment]
Hi @sp1thas I would like to work on this issue

**Comment by sahilbansal17** [comment]
@Simba-97 Have you started working on this? I was thinking to pick if it is still open.

**Comment by Simba-97** [comment]
@sahilbansal17 Yes, I have started working on this issue.

**Comment by Simba-97** [comment]
@sp1thas Could you explain me about how we are expecting to split the filename based on the new config value?

**Comment by sp1thas** [comment]
@Simba-97 

given this filename: `69e0ed49764ae1cae751fd7a78d45407.pdf`

the slit should work like this:

 - `FOLDER_TREE_LENGTH=1` (this should be the default): `6/9/e/69e0ed49764ae1cae751fd7a78d45407.pdf`
 - `FOLDER_TREE_LENGTH=2`: `69/e0/ed/69e0ed49764ae1cae751fd7a78d45407.pdf`
 - `FOLDER_TREE_LENGTH=3`: `69e/0ed/497/69e0ed49764ae1cae751fd7a78d45407.pdf`
 ...

**Comment by sp1thas** [comment]
@Simba-97 is it clean how you should create the folder structure? Do you need further guidance?

**Comment by Simba-97** [comment]
Hey @sp1thas , yeah I got the idea behind the folder structure. I'll soon create a PR for this.

**Comment by HemantSachdeva** [comment]
> @Simba-97
> 
> given this filename: `69e0ed49764ae1cae751fd7a78d45407.pdf`
> 
> the slit should work like this:
> 
> * `FOLDER_TREE_LENGTH=1` (this should be the default): `6/9/e/69e0ed49764ae1cae751fd7a78d45407.pdf`
> * `FOLDER_TREE_LENGTH=2`: `69/e0/ed/69e0ed49764ae1cae751fd7a78d45407.pdf`
> * `FOLDER_TREE_LENGTH=3`: `69e/0ed/497/69e0ed49764ae1cae751fd7a78d45407.pdf`
>   ...

Hey, what should be the depth of the file?
Above you said that if `FOLDER_TREE_LENGTH` = 2 then the path should be `ab/cd/abcdefg.png` which shows the depth is also 2 (*/*/basename.png) but now you are defining depth=3 for all the lengths.

**Comment by Simba-97** [comment]
@HemantSachdeva Yes, the default value of the TREE_DEPTH is 3 now.

**Comment by HemantSachdeva** [comment]
Below is the working code sample.

```py
import os


def build_path(depth=3,
               length=3,
               filename="69e0ed49764ae1cae751fd7a78d45407.pdf"):

    return os.path.join(*[filename[i:i + length] for i in range(0, depth * length, length)], filename)
```

I am busy somewhere so I can't spend time understanding the complete workflow of the project to adapt my code so I am just dropping the main part. Hope you keep the proper authorship XD.

**Comment by Simba-97** [comment]
@sp1thas Please review both of the linked PRs and please do let us know if anything needs to be changed or modified.
